proxy_cache_path /var/cache/nginx/iptv
    levels=1:2
    keys_zone=iptv_cache:200m
    max_size=30g
    inactive=30m
    use_temp_path=off;

log_format edge_iptv '$time_iso8601|$remote_addr|$request_method|$uri|$status|$body_bytes_sent|$request_time|$upstream_addr|$upstream_status|$upstream_cache_status|$http_user_agent';

server {
    listen 5001;
    server_name _;

    charset utf-8;

    access_log /var/log/nginx/edge_access.log edge_iptv;
    error_log /var/log/nginx/edge_error.log warn;

    location = /health {
        proxy_pass http://127.0.0.1:5010/health;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }

    location = /panel {
        proxy_pass http://127.0.0.1:5010/panel;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }

    location = / {
        proxy_pass http://127.0.0.1:5010/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }

    # Proxy dinámico desde el Origin Central.
    # Ejemplo:
    # /proxy/1480473495.ts
    location ~ ^/proxy/([0-9]+)\.ts$ {
        proxy_pass http://10.254.1.11:4001/proxy/$1.ts;
        proxy_http_version 1.1;

        proxy_set_header Host 10.254.1.11:4001;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";

        proxy_connect_timeout 10s;
        proxy_send_timeout 3600s;
        proxy_read_timeout 3600s;

        proxy_buffering on;
        proxy_request_buffering off;

        proxy_cache iptv_cache;
        proxy_cache_key "$scheme$proxy_host$request_uri";
        proxy_cache_valid 200 206 15s;
        proxy_cache_lock on;
        proxy_cache_lock_timeout 10s;
        proxy_cache_lock_age 10s;
        proxy_cache_use_stale updating error timeout http_500 http_502 http_503 http_504;

        add_header X-Edge-Cache $upstream_cache_status always;
        add_header X-Edge-Node "EDGE-ANCASTI-01" always;

        default_type video/mp2t;

        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }
}